# Generated by Django 5.2 on 2025-04-30 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0119_alter_channel_kind"),
        ("api", "0120_check_req_failure_kw_check_req_start_kw_and_more"),
    ]

    operations = []
