# Generated by Django 5.2 on 2025-04-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0121_merge_20250430_1848"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="max_duration",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="check",
            name="min_duration",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="ping",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
